# Generated by Django 6.0.4 on 2026-04-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbrella_cap', models.IntegerField()),
                ('gallon', models.IntegerField()),
                ('gallon_cap', models.IntegerField()),
                ('cap_sticker', models.IntegerField()),
                ('rock_salt', models.IntegerField()),
            ],
        ),
    ]
