# Generated by Django 6.0.4 on 2026-05-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='cap_sticker',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='gallon',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='gallon_cap',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='rock_salt',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='umbrella_cap',
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_1',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_2',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_3',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_4',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_5',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_6',
            field=models.IntegerField(default=50),
        ),
    ]
