# Generated by Django 6.0.3 on 2026-05-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product_6',
        ),
    ]
