# Generated by Django 6.0.3 on 2026-05-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_remove_inventory_product_6'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('customerName', models.CharField(max_length=255)),
                ('orderType', models.CharField(max_length=50)),
                ('deliveryAddress', models.TextField(blank=True, null=True)),
                ('contactNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('items', models.JSONField()),
                ('totalAmount', models.FloatField()),
                ('paymentMethod', models.CharField(default='cash', max_length=50)),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
    ]
